version: "3"

services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_DB: uch
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "uch", "-U", "user" ]
      interval: 30s
      timeout: 60s
      retries: 5

  redis:
    image: redis:7
    #command: redis-server --requirepass sOmE_sEcUrE_pAsS
    #environment:
    #  REDIS_HOST: queque
    #  REDIS_PORT: 6379
    #  REDIS_PASSWORD: sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"

  

#volumes:
#  db-data: