# Generated by Django 5.0 on 2024-01-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('topic', models.TextField(max_length=128)),
                ('message_text', models.TextField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
