# Generated by Django 5.0 on 2024-01-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_contactsmessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactsMessages',
            new_name='ContactMessage',
        ),
    ]
