# Generated by Django 5.0 on 2024-02-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_myedu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myedu',
            name='courses',
        ),
        migrations.AddField(
            model_name='myedu',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course'),
            preserve_default=False,
        ),
    ]
