# Generated by Django 5.0 on 2024-01-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_contactmessage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.TextField(default='Незнакомец'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message_text',
            field=models.TextField(default='Пусто', max_length=512),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='topic',
            field=models.TextField(default='Вопрос с сайта', max_length=128),
        ),
    ]
