# Generated by Django 5.0 on 2023-12-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycourse',
            name='description',
            field=models.TextField(default='Описание направления', max_length=1024),
        ),
    ]
