# Generated by Django 5.0 on 2023-12-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_categorycourse_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycourse',
            name='description',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
