# Generated by Django 5.0 on 2024-01-15 14:52

import userapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_scuser_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=userapp.models.user_directory_path, verbose_name='Фотография'),
        ),
    ]
