# Generated by Django 5.0 on 2024-01-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_scuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scuser',
            name='photo',
            field=models.TextField(default='', null=True),
        ),
    ]
